In [8]:
import open3d as o3d
import numpy as np

# Load binary point cloud
bin_pcd = np.fromfile("../DriveData/2024-09-09/Export/pointcloud/data/0000001280.bin", dtype=np.float32)
print(bin_pcd)

# Reshape and drop reflection values
points = bin_pcd.reshape((-1, 4))[:, 0:3]
#points = bin_pcd
print(points)

# Convert to Open3D point cloud
o3d_pcd = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(points))

# Save to whatever format you like
o3d.io.write_point_cloud("pointcloud.pcd", o3d_pcd)

print("Load a ply point cloud, print it, and render it")
pcd = o3d.io.read_point_cloud('pointcloud.pcd')
print(pcd)
print(np.asarray(points))
o3d.visualization.draw_geometries([pcd])


[-2.6248430e+01  3.8540568e-03  5.3796768e+00 ... -7.7511035e-02
 -2.3694139e+00  4.0000000e+00]
[[-2.62484303e+01  3.85405682e-03  5.37967682e+00]
 [-2.64047375e+01  1.65902689e-01  5.41138411e+00]
 [-2.64884892e+01  3.28978240e-01  5.42862511e+00]
 ...
 [-1.25961895e+01 -2.31022522e-01 -2.33565784e+00]
 [-1.26926222e+01 -1.54899418e-01 -2.35395026e+00]
 [-1.27738609e+01 -7.75110349e-02 -2.36941385e+00]]
Load a ply point cloud, print it, and render it
PointCloud with 131072 points.
[[-2.62484303e+01  3.85405682e-03  5.37967682e+00]
 [-2.64047375e+01  1.65902689e-01  5.41138411e+00]
 [-2.64884892e+01  3.28978240e-01  5.42862511e+00]
 ...
 [-1.25961895e+01 -2.31022522e-01 -2.33565784e+00]
 [-1.26926222e+01 -1.54899418e-01 -2.35395026e+00]
 [-1.27738609e+01 -7.75110349e-02 -2.36941385e+00]]
