In [1]:
import open3d as o3d
import numpy as np

# Load binary point cloud
bin_pcd = np.fromfile("./bin/678.bin", dtype=np.float32)
print(bin_pcd)

# Reshape and drop reflection values
points = bin_pcd.reshape((-1, 4))[:, 0:3]
#points = bin_pcd
print(points)

# Convert to Open3D point cloud
o3d_pcd = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(points))

# Save to whatever format you like
o3d.io.write_point_cloud("pointcloud.pcd", o3d_pcd)

print("Load a ply point cloud, print it, and render it")
pcd = o3d.io.read_point_cloud('pointcloud.pcd')
print(pcd)
print(np.asarray(points))
o3d.visualization.draw_geometries([pcd])


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
[-1.5505795e+01  1.8619292e-03  3.2077272e+00 ... -5.7222344e-02
 -1.7355924e+00  1.0800000e+02]
[[-1.5505795e+01  1.8619292e-03  3.2077272e+00]
 [-8.3376694e+00  5.1692646e-02  1.7585057e+00]
 [-8.3724785e+00  1.0329021e-01  1.7656398e+00]
 ...
 [-9.4865408e+00 -1.7374042e-01 -1.7384211e+00]
 [-9.4756441e+00 -1.1538409e-01 -1.7361580e+00]
 [-9.4732275e+00 -5.7222344e-02 -1.7355924e+00]]
Load a ply point cloud, print it, and render it
PointCloud with 131072 points.
[[-1.5505795e+01  1.8619292e-03  3.2077272e+00]
 [-8.3376694e+00  5.1692646e-02  1.7585057e+00]
 [-8.3724785e+00  1.0329021e-01  1.7656398e+00]
 ...
 [-9.4865408e+00 -1.7374042e-01 -1.7384211e+00]
 [-9.4756441e+00 -1.1538409e-01 -1.7361580e+00]
 [-9.4732275e+00 -5.7222344e-02 -1.7355924e+00]]
